### ISSUE TITLE
[BUG] with cooling fan and sd card

### ISSUE THREAD

**Issue by Kaspervape** [Foxies-CSTL/Marlin_2.1.x#10]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

new: i tried with vscode, controlled on configation.h and adv, same problems "media init fail" and pid for fan cooler (i use 5015)

i'm using 2.1.1 on my Q5 , the cooling fan is so bugged , on 0% made a little movements, when i put on 100% she go on 50% and 30% but she change his rpm casually. 
for the sd card, it isn't recognized from the sistem , the other things are ok.
i used Q5v1.3_8CWBPULR-Robin_nano35 .
ps. with stock firmware it's all fine

### Version of Marlin Firmware

2.1.1

### Printer model

flsun q5 

### Electronics

nano v.1.3

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Cura

### Host Software

SD Card (headless)

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Q5v1.3_8CWBPULR-Robin_nano35.zip](https://github.com/Foxies-CSTL/Marlin_2.1.x/files/9971448/Q5v1.3_8CWBPULR-Robin_nano35.zip)

**Comment by Foxies-CSTL** [comment]
I'm going to redo the same firmware (4x2208 standalone+BMG) and put it on the "Firmwares" branch, in the "Support&Tests" directory.
But check that the power supply voltage coming to your MoBo is 24.5v otherwise adjust it (info on the Wiki).
=> [T2-Q5v1.3_8CWBPULR-Robin_nano35.bin](https://github.com/Foxies-CSTL/Marlin_2.1.x/tree/Firmwares/SUPPORT%26TESTs/
)
