### ISSUE TITLE
[FR] Request firmware

### ISSUE THREAD

**Issue by capkalu** [Foxies-CSTL/Marlin_2.1.x#15]
### Is your feature request related to a problem? Please describe.

No

### Are you looking for hardware support?

No

### Describe the feature you want

Request following firmware for the SR:
SRM-SDXHZPULR32-Robin_nano_v3.bin

Thx a lot!!!

**Comment by Foxies-CSTL** [comment]
This is not the place for firmware requests but I will answer:
- There is currently no DWIN (DGUS OS4) firmware (option D) that incorporates the specific features of Deltas. The SR firmware would have been a good base to work with but the sources have never been published. It is easier and cheaper to put another screen compatible with Marlin like the MksTS35 or the TFT of the BTT-TFT family (35/50/70).
The MksH43 TFT (DWIN) works but as I said before, it lacks a lot of functions for Deltas and MKS has not updated its firmware anymore.
- The input shaping (option Z) has not been validated on the Delta printers (nor on Core, Polar or Scara) because the compensation is done on the stepper motor driver associated with the Cartesian axis, so for the moment only for all Cartesian printers. It is only a problem of time and material because the author of the algorithm does not have these printers to develop.
So for a firmware for the SR, there are many possible combinations and some are already available.
