### ISSUE TITLE
Q5_8+SCWXPULRM-Robin_nano.bin  - no direct drive (extruder to fast)

### ISSUE THREAD

**Issue by chromoxdor** [Foxies-CSTL/Marlin_2.1.x#26]
My Q5 got a direct drive extruder (micro swiss) so i decided to use the above mentioned firmware file to update from the stock firmware. Unfortunately the speed when loading filament is way too high. It looks like this is still set for a geared extruder. Or am i doing something wrong and there is a  setting i missed?

**Comment by Foxies-CSTL** [comment]
Hi,

your extruder has a different gear ratio than the original (1:1 vs 3:1) so you need to set the Estep steps to 130 instead of 410.

You can do this in the "Steps/mm" section of the "Configuration/Advanced settings" menu. Then save it, but don't forget that this is only a starting point.  The exact value can be determined by performing an ESteps setting test, of which here's a link.
https://github.com/Foxies-CSTL/Marlin_2.1.x/wiki/2.SETTINGS-THE-PRINTER#26-extruder
or
https://teachingtechyt.github.io/calibration.html#esteps

**Comment by chromoxdor** [comment]
Thanks... this is working. 
But after unloading filament the head is always crashing into the bed. any ideas why this is happening? 
I also tried it with the stock settings to see if it isn´t an issue with changing the e-steps. Same problem..

**Comment by chromoxdor** [comment]
BTW: Loading filament works fine

**Comment by Foxies-CSTL** [comment]
If your Z_Offset setting is ok, then you may have forgotten to load the correct mesh into your GCode Start (G29 L1 = for PLA mesh).
Here's a reminder at the bottom of the page.
https://github.com/Foxies-CSTL/Marlin_2.1.x/blob/Firmwares/Instructions.md

**Comment by chromoxdor** [comment]
No, this seems to be kind of a bug.
To reproduce: Turn on the printer and without doing anything else unload the filament.
Usually the printer lifts the head a bit when unloading. This doesn´t happen when freshly turned on!
But the printer does want to move the head down again... 😳

Edit:

> If your Z_Offset setting is ok, then you may have forgotten to load the correct mesh into your GCode Start (G29 L1 = for PLA mesh).
> Here's a reminder at the bottom of the page.
> https://github.com/Foxies-CSTL/Marlin_2.1.x/blob/Firmwares/Instructions.md


To be clear, I did follow these steps before

**Comment by chromoxdor** [comment]
I also have a small side question. I successfully build my own firmware. It works so far, but i also want the background to be black. 🙂  Where do i define this?

**Comment by Foxies-CSTL** [comment]
> But the printer does want to move the head down again... 😳

This is normal, as a Delta doesn't know where it is at start-up, unless you do a "Home" before operations;

> but i also want the background to be black. 🙂 Where do i define this?

The "Theme" option will be available with future 2.1.3 ;-) but if it's just the background, you'll need to insert a line in your build:
#define COLOR_BACKGROUND COLOR_DARK

**Comment by chromoxdor** [comment]
> This is normal, as a Delta doesn't know where it is at start-up, unless you do a "Home" before operations;

That might be, but why has the head to move after a filament change anyway. Or why doesn´t it simply home before. (exception is of course a filament change on pause)
I use now an autostart file which homes he printer when turning on.
But I do not really understand the workings of this... when i home the printer and the steppers turning off afterwards, the head is slowly moving down because of gravity and the printer actually do not know where the printhead is in that moment. 
So why behaves the filament change differently then?

Here the two scenarios:
1.  turn on printer -> start unloading filament -> unloading finished an head lowers and crashes
2. turn on printer -> homing -> steppers off -> head moves to buildplate because of gravity ->  start unloading filament -> head moves up a bit -> filament unloads -> unloading finished head moves down a bit.

> The "Theme" option will be available with future 2.1.3 ;-)

That sounds interesting :)

> #define COLOR_BACKGROUND COLOR_DARK

Thanks a lot for your help!

**Comment by Foxies-CSTL** [comment]
> * turn on printer -> start unloading filament -> unloading finished an head lowers and crashes
> 
> * turn on printer -> homing -> steppers off -> head moves to buildplate because of gravity ->  start unloading filament -> head moves up a bit -> filament unloads -> unloading finished head moves down a bit.

There are options to activate in the main configuration to block the Z axis, but there is also an adjustment to be made on your eccentric wheels to prevent the assembly from descending towards the bed.

Otherwise, filament change is automatic in two sequences, whatever the position of the head: a park movement (XYZ) then an E movement for loading/unloading the filament.



> > The "Theme" option will be available with future 2.1.3 ;-)
> 
> That sounds interesting :)

* ===========News feature for V2.1.3 ==========
* Change EEPROM reset with disable(M593 F0) IS to prepare your Delta without IS enable. 
* Add mode portrait for TFT32/TS35.
* New MoBo temp.
* New stm32f1.ini (hispeed)
* add state time/restant
* Show the E position (filament used) during printing
* Show the last file on first place.
* New theme DELTAFOX.
* disable UBL_HILBERT and enable UBL_TILT
* New menu for filament (runout lengh, time)
* New menu for Auto-Sleep screen to 0 at 99mn screenview. (M255 S5)
* etc

**Comment by chromoxdor** [comment]
Hey Foxies, 

i have another question. I do not use Facebook so i am not sure where to ask this other than here. I don´t want to open a new issue for this so i extend this one.
If this is not ok and there is another way of asking this, please point me to it.

I cloned your marlin repo and changed besides the e-steps and the black backgorund nothing in the config so far.
It works fine except homing. When homing from the bottom of the bed it stops around 1cm before the endstops and gives the error "homing failed" (everything is calibrated as in your precompiled binaries and there it also works correctly). 
I assume there must be an issue in the configuration regarding z height since the printer expects to reach the endpoint 1cm earlier. What do i miss? 
Thanks in advance!

**Comment by Foxies-CSTL** [comment]
> so i am not sure where to ask this other than here.

I'm on Discord on the Marlin or FLSUN server.
Flsun = "https://discord.gg/m8hbjpTM49"
Marlin = "https://discord.gg/SucfDN8Z"
See you soon ;-)
