### ISSUE TITLE
MKS Nanov1.3 socket labeled SD_Extender [BUG]

### ISSUE THREAD

**Issue by riccalisci** [Foxies-CSTL/Marlin_2.1.x#4]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

``the SD card inserted in the external SD reader is recognized correctly but when printing is started, the printer resets when the set temperature is reached.
With the same gcode file in the micro SD inserted in the original slot, works.
https://youtu.be/gPnYbzBWXPY

### Bug Timeline

problem found in 2.1.0 version too

### Version of Marlin Firmware

2.1.1

### Printer model

Flsun Q5

### Electronics

MKS Robin Nano 1.3

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

IdeaMaker

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[confguration.zip](https://github.com/Foxies-CSTL/Marlin_2.1.x/files/9269063/confguration.zip)

**Comment by Foxies-CSTL** [comment]
Hi @riccalisci  
Sorry but I was busy with the preparation of the 2.1.1. Does the problem persist with this version?

**Comment by riccalisci** [comment]
yes, i'have tested also 2.1.1 (beta version) and problem still exist

**Comment by Foxies-CSTL** [comment]
> yes, i'have tested also 2.1.1 (beta version) and problem still exist

I'm talking about the 2.1.1 version of 27/08/2021, not the bugfix. 
Did you perform a Nozzle PID in the preparation of your printer after leveling for PLA?

**Comment by riccalisci** [comment]
i can try a new stabile versione 2.1.1, could it have been fixed?
Yes, i've perform a nozzle and bed PID.

**Comment by riccalisci** [comment]
i've tried with 2.1.1 and 2.0.9.3 versione, same issue.

**Comment by Foxies-CSTL** [comment]
Hi,
As you are using a Q5 with MoBo nanoV1.3, I think that in the definition of the pins, the part where the use of external extension for a card reader (card socket) is missing. When I made my pin definition, I added this part because the HiSpeedV1 has this connector but I did not validate it with hardware.

MoBo NanoV1.x
![image](https://user-images.githubusercontent.com/24864147/199113756-d72682a6-091a-4ae9-bc1d-7d5f89600d14.png)

MoBo HiSpeedV1
![image](https://user-images.githubusercontent.com/24864147/199113910-0a21443a-80c5-410d-8a66-3a70e11a4b09.png)

Maybe adding this part in the pin file, could help you.

**Comment by riccalisci** [comment]
Thanks!
I can try it,  but i saw that the pins are the same from schematics.
![Immagine 2022-11-07 130437](https://user-images.githubusercontent.com/78355311/200306104-e280a757-dd99-4e74-bd37-fd79997f027b.png)
[MKS Robin Nano V1.3_002 SCH.pdf](https://github.com/Foxies-CSTL/Marlin_2.1.x/files/9951239/MKS.Robin.Nano.V1.3_002.SCH.pdf)

**Comment by riccalisci** [comment]
i tried to set at half SPI speed, but nothing has changed.

**Comment by Foxies-CSTL** [comment]
Sorry but I can't help you more.
